### ISSUE TITLE
Not Updated

### ISSUE THREAD

**Issue by NeilMD** [dinosaurfiles/cybrary-video-downloader#1]
Please update this.I was able to edit few lines, but there are still problems. I want to learn pentesting. Im new to github so I dont know how to message you. I hope you can update the cybrary downloader that you have created. I really really want to learn. Thanks!

**Comment by dinosaurfiles** [comment]
Hi @NeilMD! Please specifiy OS and Python version used. Also please post details of the error.

**Comment by NeilMD** [comment]
Manjaro. For the Python I think the latest version (Sorry, Im in windows and doing some HW i dont want to change right now). Ive already  change some of the codes to the latest syntax of python. There are no error messages but when ever it says download complete there is no file. Ill give you the codes later.

**Comment by NeilMD** [comment]
[cybrary--edited.zip](https://github.com/dinosaurfiles/cybrary-video-downloader/files/288345/cybrary--edited.zip)

**Comment by dinosaurfiles** [comment]
Hi@NeilMD, please check the new update (0.3). I've updated and cleaned the project based on the current scheme. Enjoy!

PS: Open another issue for requests or bugs!
