### ISSUE TITLE
Download problem with error 'raw_input' is not defined

### ISSUE THREAD

**Issue by marlonbriguera** [dinosaurfiles/cybrary-video-downloader#13]
I'm having trouble downloading with the error below without reaching the stage of having username and password prompts

OS: Windows 7
Python version Python 3.5.3

python cybrary-video-downloader.py --quality 720 --course "https://www.cybrary.it/course/secure-coding/"
Traceback (most recent call last):
  File "cybrary-video-downloader.py", line 74, in <module>
    main()
  File "cybrary-video-downloader.py", line 68, in main
    username = raw_input("Username: ")
NameError: name 'raw_input' is not defined

**Comment by dinosaurfiles-zz** [comment]
Hi! Please see the README.md again, the program is using **Python 2.7** and **not Python 3.5**.
