### ISSUE TITLE
Resume download if connection fails.

### ISSUE THREAD

**Issue by Zvezke** [dinosaurfiles/cybrary-video-downloader#15]
I guess that this isn't actually an issue (bug), but rather a suggestion.
I downloaded their 'Network +' course, and my connection failed missing the last four videos. As far as I understand, I have to redownload the entire course (app. 50 gb) to get the last four videos. Am I misunderstanding something? It not – Is it possible to add the feature to download individual videos or resume downloads?

... and btw, thanks a lot for this brilliant program. I really appreciate it.

**Comment by dinosaurfiles-zz** [comment]
Hi @Zvezke! The downloader definitely resumes the downloading of the videos but unfortunately it traverses each lesson at every run so I might close this issue. As for the aforementioned ` download individual videos` feature, we could create a new issue for that. Thank you!
