### ISSUE TITLE
Raw input is not defined error

### ISSUE THREAD

**Issue by Adarsh777** [dinosaurfiles/cybrary-video-downloader#17]
Hi , 
I facing below error Please help me to fix it.
 ```
Traceback (most recent call last):
  File "cybrary-video-downloader.py", line 74, in <module>
    main()
  File "cybrary-video-downloader.py", line 68, in main
    username = raw_input("Username:")
NameError: name 'raw_input' is not defined
```
Thank You

**Comment by dinosaurfiles-zz** [comment]
Hi @Adarsh777! I think you're definitely using **Python 3.x** rather than **Python 2.7** as defined in the [requirements](https://github.com/dinosaurfiles/cybrary-video-downloader#requirements) of the program.  I'm closing this issue right now.
