### ISSUE TITLE
Not working for new version of cybrary please update

### ISSUE THREAD

**Issue by krisk248** [dinosaurfiles/cybrary-video-downloader#23]
Hello,
         I am a great fan of this downloader but the new version of cybrary has been updated in the web I just want you guys to update the downloader for the new version of the cybrary please. Its a humble request for you .

**Comment by Status-418** [comment]
If you change line 45 to:
```
    for lessonLink in parsedCourseHTML.find_all('a', attrs={'class':'modulehover'}):
```

that should do the trick.

**Comment by krisk248** [comment]
Thank you once i try it i will inform you thank you a a lot @Status-418

**Comment by krisk248** [comment]
Thank the code worked just fine and it was a great help @Status-418 thank you so much so much.....


👍 👍 👍 👍 👍 💯 🥇 💯 👍
