### ISSUE TITLE
Resumable

### ISSUE THREAD

**Issue by NeilMD** [dinosaurfiles/cybrary-video-downloader#3]
Hi @dinosaurfiles! The files are good but  I wonder if i can resume my downloads. I tried downloading networking+ but I wont be able to finish it in a night. How do I able to continue where  I was before with downloading the networking+ again from the start. Thanks!

**Comment by dinosaurfiles** [comment]
Hi again @NeilMD! Any interrupted downloads from Cybrary will continue to download as soon as you start the program again. Mind that the video quality should be the same when you continue to download the videos.

Keep those requests coming! :smile: :+1:
