### ISSUE TITLE
Was working fine until today

### ISSUE THREAD

**Issue by b4ckd00r** [dinosaurfiles/cybrary-video-downloader#5]
It was working fine until today i started getting this error as soon as i launch the script

Downloading https://www.cybrary.it/video/phases-penetration-testing-intro/
Traceback (most recent call last):
  File "./cybrary-video-downloader.py", line 70, in <module>
    main()
  File "./cybrary-video-downloader.py", line 67, in main
    getLessonList(sys.argv[2], sys.argv[1])
  File "./cybrary-video-downloader.py", line 41, in getLessonList
    downloadVideos(getVideoLink(link), quality)
  File "./cybrary-video-downloader.py", line 50, in getVideoLink
    return (list(unique_everseen(videoLinkRegex.findall(lessonhtml))))[0]
IndexError: list index out of range

PS: if you could make it so that when it downloads the videos it puts them into folders according to the playlist on the website

**Comment by dinosaurfiles** [comment]
Hi! Thank you for the feedback, im trying to fix the issue right now and implement ur requested feature so hold on!

**Comment by dinosaurfiles** [comment]
Hi guys, please read [this](https://github.com/dinosaurfiles/cybrary-video-downloader#attention-september-7-2016). Thank you!
