### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by vaanffxii** [dinosaurfiles/cybrary-video-downloader#6]
I can't download
pls see below to detail.
======================================
python ./cybrary-video-downloader.py 720 "https://www.cybrary.it/course/comptia-security-plus/"
Username: *******
Password: *******
Downloading https://www.cybrary.it/video/john-oyeleke/
[vimeo] 147484510: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Downloading https://www.cybrary.it/video/firewalls/
[vimeo] 139229264: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Downloading https://www.cybrary.it/video/proxies/
^Z
======================================

pls check

thx.

**Comment by dinosaurfiles** [comment]
Hi guys, please read [this](https://github.com/dinosaurfiles/cybrary-video-downloader#attention-september-7-2016). Thank you!
